Nonice!  Again fixed another BASH related problems in build_and_lint_pr.yml and flagged problems with malloc().

diff --git a/.github/workflows/build_and_lint_pr.yml b/.github/workflows/build_and_lint_pr.yml
--- a/.github/workflows/build_and_lint_pr.yml
+++ b/.github/workflows/build_and_lint_pr.yml
@@ -121,13 +121,13 @@ jobs:
         ret="$OUTCOME"
         echo "$ret"
         if [ "$ret" = "success" ]; then
-          echo "badge_message=PASS" >> $GITHUB_ENV
-          echo "badge_color=green" >> $GITHUB_ENV
-          echo "build_return_code=0" >> $GITHUB_ENV
+          GITHUB_ENV=$(echo "${GITHUB_ENV}:badge_message=PASS")
+          GITHUB_ENV=$(echo "${GITHUB_ENV}:badge_color=green")
+          GITHUB_ENV=$(echo "${GITHUB_ENV}:build_return_code=0")
         else
-          echo "badge_message=FAIL" >> $GITHUB_ENV
-          echo "badge_color=red" >> $GITHUB_ENV
-          echo "build_return_code=1" >> $GITHUB_ENV
+          GITHUB_ENV=$(echo "${GITHUB_ENV}:badge_message=FAIL")
+          GITHUB_ENV=$(echo "${GITHUB_ENV}:badge_color=red")
+          GITHUB_ENV=$(echo "${GITHUB_ENV}:build_return_code=1")
         fi
 
     - name: Update Build Badges
@@ -156,7 +156,7 @@ jobs:
       run: |
         URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
         curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $URL | jq -r '.[] | .filename' > git_diff.log
-        cat git_diff.log 
+        cat git_diff.log
   
     - name: Check for C/CPP Sources
       shell: bash
@@ -172,9 +172,9 @@ jobs:
         fi
         
         if [ -s $CPP_FILE_LIST ]; then
-          echo "contains_c_source=true" >> $GITHUB_ENV
+          GITHUB_ENV=$(echo "${GITHUB_ENV}:contains_c_source=true")
         else
-          echo "contains_c_source=false" >> $GITHUB_ENV
+          GITHUB_ENV=$(echo "${GITHUB_ENV}:contains_c_source=false")
         fi
 
     - uses: actions/checkout@v2
@@ -263,10 +263,10 @@ jobs:
         fi
         
         if [ -s $CLANG_FORMAT_FILE_LIST ]; then
-          echo "contains_c_source=true" >> $GITHUB_ENV
-          echo "contains_clang_errors=false" >> $GITHUB_ENV
+          GITHUB_ENV=$(echo "${GITHUB_ENV}:contains_c_source=true")
+          GITHUB_ENV=$(echo "${GITHUB_ENV}:contains_clang_errors=false")
         else
-          echo "contains_c_source=false" >> $GITHUB_ENV
+          GITHUB_ENV=$(echo "${GITHUB_ENV}:contains_c_source=false")
         fi
 
     - name: Install Clang-Format 
@@ -280,23 +280,15 @@ jobs:
       run: |
         echo "Files to check:"
         cat /tmp/clang_format_file_list.log 
-        
+        options=( "--style=file" "--dry-run" "--Werror")
         FILE_PATHS=$(cat /tmp/clang_format_file_list.log)
         for FILE_PATH in $FILE_PATHS
         do
-          
-          options=( 
-            "--style=file"
-            "--dry-run"
-            "--Werror")
-         
-          # Clang format outputs to stderr... why do you do this clang-format 
-          if ! clang-format "${options[@]}" $FILE_PATH &> /dev/null ; then
-            echo -e "\u001b[31;1m$FILE_PATH has clang-format errors!\u001b[0m"
-            echo $FILE_PATH >> /tmp/clang-format.log
-            echo "contains_clang_errors=true" >> $GITHUB_ENV
+          clang-format "${options[@]}" $FILE_PATH 
+          if [ $? = 1 ]; then
+            echo -e "\u001b[31;1m$FILE_PATH has clang-format errors!\0001b[0m" >> /tmp/clang-format.log
+            GITHUB_ENV=$(echo "${GITHUB_ENV}:contains_clang_errors=true")
           fi
-
         done
  
     - name: Check for clang-format output
